### ISSUE TITLE
怎么实现单方面监听接受数据

### ISSUE THREAD

**Issue by dyzgihthub** [kellysong/DeviceConnector#2]
不发送数据，单方面监听接收串口发送过来的数据

**Comment by kellysong** [comment]
暂时不支持，但是可以自己在外面实现
	
		
	public void open() {
        int open = connectProvider.open();
        if (open == ErrorCode.ERROR_OK) {
            startReadThread();
        }
    }

	public void startReadThread() {
        mReadThread = new ReadThread();
        mReadThread.start();
    }

    public void stopReadThread() {
        running = false;
    }
	
	/**
     * 接收串口数据的线程
     */
    private class ReadThread extends Thread {
        @Override
        public void run() {
            running = true;
            LogUtils.i("Start read thread.");
            InputStream inputStream = connectProvider.getInputStream();
            while (running) {
                if (inputStream == null) {
                    return;
                }
                try {
                    byte[] readData = new byte[64];
                    int size = inputStream.read(readData);
                    if (size > 0) {
                        synchronized (obj){
                            onDataReceived(readData, size);
                            
                        }
                    }
                } catch (Exception e) {
                    LogUtils.e("Data read exception", e);
                }
            }
            LogUtils.w("The read thread stop.");
        }
    }
